services:
  - type: web
    name: zulgap-ai
    env: python
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ..
      cp -r frontend/build backend/build
      pip install -r requirements.txt
    startCommand: gunicorn backend.main:app